### ISSUE TITLE
No place to donate ☕ 

### ISSUE THREAD

**Issue by emragins** [saikatdas0790/svelte-environment-variables#2]
I was trying to hook up environment variables and ran into the "process not defined" issue.

The top search results showed a bunch of work arounds using session -- gross.

This and it worked like a charm with my existing pattern of using env-cmd and saved me much time and heart ache.  I would happily buy you a coffee (or whatever).

Thank you for making this and for making it easy to use! 😄

**Comment by saikatdas0790** [comment]
@emragins Thank you for the kind words. I created this lib for the exact same reasons you mentioned to scratch my own itch.

Since this is my first published npm package, I wasn't too familiar with the donation workflow and never got around to setting it up.

However, I've set up Coinbase now to accept crypto payments [here](https://commerce.coinbase.com/checkout/b535d9cf-394b-4337-a10e-32a3fcf96b0a) in case you're still feeling generous. Appreciate the kind words nonetheless. Cheers.
